### ISSUE TITLE
KeyError: 'hydropathy' while running design_pdb.py

### ISSUE THREAD

**Issue by Thoudam-A** [pengzhangzhi/ab_opt#9]
Hi, thanks for excellent work!
I ran command like this: python design_pdb.py ./data/examples/8X0Y_complex.pdb   --config ./configs/test/codesign_single.yml
and encountered an error, the result is:

---
┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2024 [Rosetta PyRosetta4.Release.python38.ubuntu 2024.19+release.a34b73c40fe9c61558d566d6a63f803cfb15a4fc 2024-05-02T16:22:03] retrieved from: http://www.pyrosetta.org
┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2024 [Rosetta PyRosetta4.Release.python38.ubuntu 2024.19+release.a34b73c40fe9c61558d566d6a63f803cfb15a4fc 2024-05-02T16:22:03] retrieved from: http://www.pyrosetta.org
[INFO] Renumbered chain F (K)
[INFO] Chain B does not contain valid Fv: Variable chain sequence not recognized: "TNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLAPATVCGPK"
[INFO] Renumbered chain E (H)
[2024-09-16 10:29:59,816::sample::INFO] Data ID: 8X0Y_complex.pdb
[2024-09-16 10:29:59,816::sample::INFO] Results will be saved to ./results/codesign_single/8X0Y_complex.pdb_2024_09_16__10_29_59
[2024-09-16 10:29:59,917::sample::INFO] Loading model config and checkpoints: trained_models/ckpt.pt
[2024-09-16 10:31:14,701::sample::INFO] <All keys matched successfully>
[2024-09-16 10:31:14,858::sample::INFO] Start sampling for: H_CDR3
Sampling:   0%|                                                                                                                            | 0/500 [00:00<?, ?it/s]
8X0Y_complex.pdb-H_CDR3:   0%|                                                                                                               | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "design_pdb.py", line 4, in <module>
    design_for_pdb(args_from_cmdline())
  File "/home/disk02/ab_design/zrx/ab_opt-main/AbDesign/diffab/tools/runner/design_for_pdb.py", line 200, in design_for_pdb
    traj_batch = model.sample(batch, sample_opt={
  File "/home/disk02/ab_design/miniconda3/envs/diffab/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/disk02/ab_design/zrx/ab_opt-main/AbDesign/diffab/models/diff_gnn.py", line 262, in sample
    hydropathy = batch['hydropathy'][batch['mask']] 
`KeyError: 'hydropathy'`

----
How can I fix it? I tried to set the attribute ‘hydropathy’ false, but it didn't work.
I'll be very grateful for your response!

**Comment by xiaoxuc** [comment]
I encountered the same problem. How did you solve it?

**Comment by pengzhangzhi** [comment]
sorry it's been too long for me to understand this code
